//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Product
{
    public int Id { get; set; }
    public string naziv { get; set; }
    public string opis { get; set; }
    public string kategorija { get; set; }
    public string proizvodjac { get; set; }
    public string dobavljac { get; set; }
    public string cena { get; set; }
}
